# Generated by Django 3.0.3 on 2020-05-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad_aire', '0002_auto_20200518_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calidad_aire',
            name='type',
        ),
        migrations.RemoveField(
            model_name='calidad_aire',
            name='value',
        ),
    ]
